/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _mainLayoutRouteImport } from './routes/__mainLayout'
import { Route as _authLayoutRouteImport } from './routes/__authLayout'
import { Route as _authLayoutIndexRouteImport } from './routes/__authLayout/index'
import { Route as _mainLayoutHomeRouteImport } from './routes/__mainLayout/home'
import { Route as _authLayoutSignUpRouteImport } from './routes/__authLayout/sign-up'
import { Route as _authLayoutSignInRouteImport } from './routes/__authLayout/sign-in'
import { Route as _mainLayoutSeriesIndexRouteImport } from './routes/__mainLayout/series/index'
import { Route as _mainLayoutProfileIndexRouteImport } from './routes/__mainLayout/profile/index'
import { Route as _mainLayoutMovieIndexRouteImport } from './routes/__mainLayout/movie/index'
import { Route as _mainLayoutAnimeIndexRouteImport } from './routes/__mainLayout/anime/index'
import { Route as _mainLayoutSeriesMediaIdRouteImport } from './routes/__mainLayout/series/$mediaId'
import { Route as _mainLayoutPersonPersonIdRouteImport } from './routes/__mainLayout/person/$personId'
import { Route as _mainLayoutMovieMediaIdRouteImport } from './routes/__mainLayout/movie/$mediaId'
import { Route as _mainLayoutCompanyCompanyIdRouteImport } from './routes/__mainLayout/company/$companyId'
import { Route as _mainLayoutAnimeMediaIdRouteImport } from './routes/__mainLayout/anime/$mediaId'
import { Route as _mainLayoutSeriesMediaIdOverviewRouteImport } from './routes/__mainLayout/series/$mediaId/overview'
import { Route as _mainLayoutAnimeMediaIdOverviewRouteImport } from './routes/__mainLayout/anime/$mediaId/overview'
import { Route as _mainLayoutSeriesMediaIdSeasonSeasonNumberIndexRouteImport } from './routes/__mainLayout/series/$mediaId/season/$seasonNumber/index'
import { Route as _mainLayoutAnimeMediaIdSeasonSeasonNumberIndexRouteImport } from './routes/__mainLayout/anime/$mediaId/season/$seasonNumber/index'

const _mainLayoutRoute = _mainLayoutRouteImport.update({
  id: '/__mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const _authLayoutRoute = _authLayoutRouteImport.update({
  id: '/__authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const _authLayoutIndexRoute = _authLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _authLayoutRoute,
} as any)
const _mainLayoutHomeRoute = _mainLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _authLayoutSignUpRoute = _authLayoutSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => _authLayoutRoute,
} as any)
const _authLayoutSignInRoute = _authLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => _authLayoutRoute,
} as any)
const _mainLayoutSeriesIndexRoute = _mainLayoutSeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutProfileIndexRoute = _mainLayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutMovieIndexRoute = _mainLayoutMovieIndexRouteImport.update({
  id: '/movie/',
  path: '/movie/',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutAnimeIndexRoute = _mainLayoutAnimeIndexRouteImport.update({
  id: '/anime/',
  path: '/anime/',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutSeriesMediaIdRoute =
  _mainLayoutSeriesMediaIdRouteImport.update({
    id: '/series/$mediaId',
    path: '/series/$mediaId',
    getParentRoute: () => _mainLayoutRoute,
  } as any)
const _mainLayoutPersonPersonIdRoute =
  _mainLayoutPersonPersonIdRouteImport.update({
    id: '/person/$personId',
    path: '/person/$personId',
    getParentRoute: () => _mainLayoutRoute,
  } as any)
const _mainLayoutMovieMediaIdRoute = _mainLayoutMovieMediaIdRouteImport.update({
  id: '/movie/$mediaId',
  path: '/movie/$mediaId',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutCompanyCompanyIdRoute =
  _mainLayoutCompanyCompanyIdRouteImport.update({
    id: '/company/$companyId',
    path: '/company/$companyId',
    getParentRoute: () => _mainLayoutRoute,
  } as any)
const _mainLayoutAnimeMediaIdRoute = _mainLayoutAnimeMediaIdRouteImport.update({
  id: '/anime/$mediaId',
  path: '/anime/$mediaId',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutSeriesMediaIdOverviewRoute =
  _mainLayoutSeriesMediaIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => _mainLayoutSeriesMediaIdRoute,
  } as any)
const _mainLayoutAnimeMediaIdOverviewRoute =
  _mainLayoutAnimeMediaIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => _mainLayoutAnimeMediaIdRoute,
  } as any)
const _mainLayoutSeriesMediaIdSeasonSeasonNumberIndexRoute =
  _mainLayoutSeriesMediaIdSeasonSeasonNumberIndexRouteImport.update({
    id: '/season/$seasonNumber/',
    path: '/season/$seasonNumber/',
    getParentRoute: () => _mainLayoutSeriesMediaIdRoute,
  } as any)
const _mainLayoutAnimeMediaIdSeasonSeasonNumberIndexRoute =
  _mainLayoutAnimeMediaIdSeasonSeasonNumberIndexRouteImport.update({
    id: '/season/$seasonNumber/',
    path: '/season/$seasonNumber/',
    getParentRoute: () => _mainLayoutAnimeMediaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof _authLayoutIndexRoute
  '/sign-in': typeof _authLayoutSignInRoute
  '/sign-up': typeof _authLayoutSignUpRoute
  '/home': typeof _mainLayoutHomeRoute
  '/anime/$mediaId': typeof _mainLayoutAnimeMediaIdRouteWithChildren
  '/company/$companyId': typeof _mainLayoutCompanyCompanyIdRoute
  '/movie/$mediaId': typeof _mainLayoutMovieMediaIdRoute
  '/person/$personId': typeof _mainLayoutPersonPersonIdRoute
  '/series/$mediaId': typeof _mainLayoutSeriesMediaIdRouteWithChildren
  '/anime/': typeof _mainLayoutAnimeIndexRoute
  '/movie/': typeof _mainLayoutMovieIndexRoute
  '/profile/': typeof _mainLayoutProfileIndexRoute
  '/series/': typeof _mainLayoutSeriesIndexRoute
  '/anime/$mediaId/overview': typeof _mainLayoutAnimeMediaIdOverviewRoute
  '/series/$mediaId/overview': typeof _mainLayoutSeriesMediaIdOverviewRoute
  '/anime/$mediaId/season/$seasonNumber/': typeof _mainLayoutAnimeMediaIdSeasonSeasonNumberIndexRoute
  '/series/$mediaId/season/$seasonNumber/': typeof _mainLayoutSeriesMediaIdSeasonSeasonNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof _authLayoutIndexRoute
  '/sign-in': typeof _authLayoutSignInRoute
  '/sign-up': typeof _authLayoutSignUpRoute
  '/home': typeof _mainLayoutHomeRoute
  '/anime/$mediaId': typeof _mainLayoutAnimeMediaIdRouteWithChildren
  '/company/$companyId': typeof _mainLayoutCompanyCompanyIdRoute
  '/movie/$mediaId': typeof _mainLayoutMovieMediaIdRoute
  '/person/$personId': typeof _mainLayoutPersonPersonIdRoute
  '/series/$mediaId': typeof _mainLayoutSeriesMediaIdRouteWithChildren
  '/anime': typeof _mainLayoutAnimeIndexRoute
  '/movie': typeof _mainLayoutMovieIndexRoute
  '/profile': typeof _mainLayoutProfileIndexRoute
  '/series': typeof _mainLayoutSeriesIndexRoute
  '/anime/$mediaId/overview': typeof _mainLayoutAnimeMediaIdOverviewRoute
  '/series/$mediaId/overview': typeof _mainLayoutSeriesMediaIdOverviewRoute
  '/anime/$mediaId/season/$seasonNumber': typeof _mainLayoutAnimeMediaIdSeasonSeasonNumberIndexRoute
  '/series/$mediaId/season/$seasonNumber': typeof _mainLayoutSeriesMediaIdSeasonSeasonNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__authLayout': typeof _authLayoutRouteWithChildren
  '/__mainLayout': typeof _mainLayoutRouteWithChildren
  '/__authLayout/sign-in': typeof _authLayoutSignInRoute
  '/__authLayout/sign-up': typeof _authLayoutSignUpRoute
  '/__mainLayout/home': typeof _mainLayoutHomeRoute
  '/__authLayout/': typeof _authLayoutIndexRoute
  '/__mainLayout/anime/$mediaId': typeof _mainLayoutAnimeMediaIdRouteWithChildren
  '/__mainLayout/company/$companyId': typeof _mainLayoutCompanyCompanyIdRoute
  '/__mainLayout/movie/$mediaId': typeof _mainLayoutMovieMediaIdRoute
  '/__mainLayout/person/$personId': typeof _mainLayoutPersonPersonIdRoute
  '/__mainLayout/series/$mediaId': typeof _mainLayoutSeriesMediaIdRouteWithChildren
  '/__mainLayout/anime/': typeof _mainLayoutAnimeIndexRoute
  '/__mainLayout/movie/': typeof _mainLayoutMovieIndexRoute
  '/__mainLayout/profile/': typeof _mainLayoutProfileIndexRoute
  '/__mainLayout/series/': typeof _mainLayoutSeriesIndexRoute
  '/__mainLayout/anime/$mediaId/overview': typeof _mainLayoutAnimeMediaIdOverviewRoute
  '/__mainLayout/series/$mediaId/overview': typeof _mainLayoutSeriesMediaIdOverviewRoute
  '/__mainLayout/anime/$mediaId/season/$seasonNumber/': typeof _mainLayoutAnimeMediaIdSeasonSeasonNumberIndexRoute
  '/__mainLayout/series/$mediaId/season/$seasonNumber/': typeof _mainLayoutSeriesMediaIdSeasonSeasonNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/home'
    | '/anime/$mediaId'
    | '/company/$companyId'
    | '/movie/$mediaId'
    | '/person/$personId'
    | '/series/$mediaId'
    | '/anime/'
    | '/movie/'
    | '/profile/'
    | '/series/'
    | '/anime/$mediaId/overview'
    | '/series/$mediaId/overview'
    | '/anime/$mediaId/season/$seasonNumber/'
    | '/series/$mediaId/season/$seasonNumber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/home'
    | '/anime/$mediaId'
    | '/company/$companyId'
    | '/movie/$mediaId'
    | '/person/$personId'
    | '/series/$mediaId'
    | '/anime'
    | '/movie'
    | '/profile'
    | '/series'
    | '/anime/$mediaId/overview'
    | '/series/$mediaId/overview'
    | '/anime/$mediaId/season/$seasonNumber'
    | '/series/$mediaId/season/$seasonNumber'
  id:
    | '__root__'
    | '/__authLayout'
    | '/__mainLayout'
    | '/__authLayout/sign-in'
    | '/__authLayout/sign-up'
    | '/__mainLayout/home'
    | '/__authLayout/'
    | '/__mainLayout/anime/$mediaId'
    | '/__mainLayout/company/$companyId'
    | '/__mainLayout/movie/$mediaId'
    | '/__mainLayout/person/$personId'
    | '/__mainLayout/series/$mediaId'
    | '/__mainLayout/anime/'
    | '/__mainLayout/movie/'
    | '/__mainLayout/profile/'
    | '/__mainLayout/series/'
    | '/__mainLayout/anime/$mediaId/overview'
    | '/__mainLayout/series/$mediaId/overview'
    | '/__mainLayout/anime/$mediaId/season/$seasonNumber/'
    | '/__mainLayout/series/$mediaId/season/$seasonNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authLayoutRoute: typeof _authLayoutRouteWithChildren
  _mainLayoutRoute: typeof _mainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__mainLayout': {
      id: '/__mainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _mainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authLayout': {
      id: '/__authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authLayout/': {
      id: '/__authLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _authLayoutIndexRouteImport
      parentRoute: typeof _authLayoutRoute
    }
    '/__mainLayout/home': {
      id: '/__mainLayout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof _mainLayoutHomeRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__authLayout/sign-up': {
      id: '/__authLayout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof _authLayoutSignUpRouteImport
      parentRoute: typeof _authLayoutRoute
    }
    '/__authLayout/sign-in': {
      id: '/__authLayout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof _authLayoutSignInRouteImport
      parentRoute: typeof _authLayoutRoute
    }
    '/__mainLayout/series/': {
      id: '/__mainLayout/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof _mainLayoutSeriesIndexRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/profile/': {
      id: '/__mainLayout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof _mainLayoutProfileIndexRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/movie/': {
      id: '/__mainLayout/movie/'
      path: '/movie'
      fullPath: '/movie/'
      preLoaderRoute: typeof _mainLayoutMovieIndexRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/anime/': {
      id: '/__mainLayout/anime/'
      path: '/anime'
      fullPath: '/anime/'
      preLoaderRoute: typeof _mainLayoutAnimeIndexRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/series/$mediaId': {
      id: '/__mainLayout/series/$mediaId'
      path: '/series/$mediaId'
      fullPath: '/series/$mediaId'
      preLoaderRoute: typeof _mainLayoutSeriesMediaIdRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/person/$personId': {
      id: '/__mainLayout/person/$personId'
      path: '/person/$personId'
      fullPath: '/person/$personId'
      preLoaderRoute: typeof _mainLayoutPersonPersonIdRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/movie/$mediaId': {
      id: '/__mainLayout/movie/$mediaId'
      path: '/movie/$mediaId'
      fullPath: '/movie/$mediaId'
      preLoaderRoute: typeof _mainLayoutMovieMediaIdRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/company/$companyId': {
      id: '/__mainLayout/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof _mainLayoutCompanyCompanyIdRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/anime/$mediaId': {
      id: '/__mainLayout/anime/$mediaId'
      path: '/anime/$mediaId'
      fullPath: '/anime/$mediaId'
      preLoaderRoute: typeof _mainLayoutAnimeMediaIdRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/series/$mediaId/overview': {
      id: '/__mainLayout/series/$mediaId/overview'
      path: '/overview'
      fullPath: '/series/$mediaId/overview'
      preLoaderRoute: typeof _mainLayoutSeriesMediaIdOverviewRouteImport
      parentRoute: typeof _mainLayoutSeriesMediaIdRoute
    }
    '/__mainLayout/anime/$mediaId/overview': {
      id: '/__mainLayout/anime/$mediaId/overview'
      path: '/overview'
      fullPath: '/anime/$mediaId/overview'
      preLoaderRoute: typeof _mainLayoutAnimeMediaIdOverviewRouteImport
      parentRoute: typeof _mainLayoutAnimeMediaIdRoute
    }
    '/__mainLayout/series/$mediaId/season/$seasonNumber/': {
      id: '/__mainLayout/series/$mediaId/season/$seasonNumber/'
      path: '/season/$seasonNumber'
      fullPath: '/series/$mediaId/season/$seasonNumber/'
      preLoaderRoute: typeof _mainLayoutSeriesMediaIdSeasonSeasonNumberIndexRouteImport
      parentRoute: typeof _mainLayoutSeriesMediaIdRoute
    }
    '/__mainLayout/anime/$mediaId/season/$seasonNumber/': {
      id: '/__mainLayout/anime/$mediaId/season/$seasonNumber/'
      path: '/season/$seasonNumber'
      fullPath: '/anime/$mediaId/season/$seasonNumber/'
      preLoaderRoute: typeof _mainLayoutAnimeMediaIdSeasonSeasonNumberIndexRouteImport
      parentRoute: typeof _mainLayoutAnimeMediaIdRoute
    }
  }
}

interface _authLayoutRouteChildren {
  _authLayoutSignInRoute: typeof _authLayoutSignInRoute
  _authLayoutSignUpRoute: typeof _authLayoutSignUpRoute
  _authLayoutIndexRoute: typeof _authLayoutIndexRoute
}

const _authLayoutRouteChildren: _authLayoutRouteChildren = {
  _authLayoutSignInRoute: _authLayoutSignInRoute,
  _authLayoutSignUpRoute: _authLayoutSignUpRoute,
  _authLayoutIndexRoute: _authLayoutIndexRoute,
}

const _authLayoutRouteWithChildren = _authLayoutRoute._addFileChildren(
  _authLayoutRouteChildren,
)

interface _mainLayoutAnimeMediaIdRouteChildren {
  _mainLayoutAnimeMediaIdOverviewRoute: typeof _mainLayoutAnimeMediaIdOverviewRoute
  _mainLayoutAnimeMediaIdSeasonSeasonNumberIndexRoute: typeof _mainLayoutAnimeMediaIdSeasonSeasonNumberIndexRoute
}

const _mainLayoutAnimeMediaIdRouteChildren: _mainLayoutAnimeMediaIdRouteChildren =
  {
    _mainLayoutAnimeMediaIdOverviewRoute: _mainLayoutAnimeMediaIdOverviewRoute,
    _mainLayoutAnimeMediaIdSeasonSeasonNumberIndexRoute:
      _mainLayoutAnimeMediaIdSeasonSeasonNumberIndexRoute,
  }

const _mainLayoutAnimeMediaIdRouteWithChildren =
  _mainLayoutAnimeMediaIdRoute._addFileChildren(
    _mainLayoutAnimeMediaIdRouteChildren,
  )

interface _mainLayoutSeriesMediaIdRouteChildren {
  _mainLayoutSeriesMediaIdOverviewRoute: typeof _mainLayoutSeriesMediaIdOverviewRoute
  _mainLayoutSeriesMediaIdSeasonSeasonNumberIndexRoute: typeof _mainLayoutSeriesMediaIdSeasonSeasonNumberIndexRoute
}

const _mainLayoutSeriesMediaIdRouteChildren: _mainLayoutSeriesMediaIdRouteChildren =
  {
    _mainLayoutSeriesMediaIdOverviewRoute:
      _mainLayoutSeriesMediaIdOverviewRoute,
    _mainLayoutSeriesMediaIdSeasonSeasonNumberIndexRoute:
      _mainLayoutSeriesMediaIdSeasonSeasonNumberIndexRoute,
  }

const _mainLayoutSeriesMediaIdRouteWithChildren =
  _mainLayoutSeriesMediaIdRoute._addFileChildren(
    _mainLayoutSeriesMediaIdRouteChildren,
  )

interface _mainLayoutRouteChildren {
  _mainLayoutHomeRoute: typeof _mainLayoutHomeRoute
  _mainLayoutAnimeMediaIdRoute: typeof _mainLayoutAnimeMediaIdRouteWithChildren
  _mainLayoutCompanyCompanyIdRoute: typeof _mainLayoutCompanyCompanyIdRoute
  _mainLayoutMovieMediaIdRoute: typeof _mainLayoutMovieMediaIdRoute
  _mainLayoutPersonPersonIdRoute: typeof _mainLayoutPersonPersonIdRoute
  _mainLayoutSeriesMediaIdRoute: typeof _mainLayoutSeriesMediaIdRouteWithChildren
  _mainLayoutAnimeIndexRoute: typeof _mainLayoutAnimeIndexRoute
  _mainLayoutMovieIndexRoute: typeof _mainLayoutMovieIndexRoute
  _mainLayoutProfileIndexRoute: typeof _mainLayoutProfileIndexRoute
  _mainLayoutSeriesIndexRoute: typeof _mainLayoutSeriesIndexRoute
}

const _mainLayoutRouteChildren: _mainLayoutRouteChildren = {
  _mainLayoutHomeRoute: _mainLayoutHomeRoute,
  _mainLayoutAnimeMediaIdRoute: _mainLayoutAnimeMediaIdRouteWithChildren,
  _mainLayoutCompanyCompanyIdRoute: _mainLayoutCompanyCompanyIdRoute,
  _mainLayoutMovieMediaIdRoute: _mainLayoutMovieMediaIdRoute,
  _mainLayoutPersonPersonIdRoute: _mainLayoutPersonPersonIdRoute,
  _mainLayoutSeriesMediaIdRoute: _mainLayoutSeriesMediaIdRouteWithChildren,
  _mainLayoutAnimeIndexRoute: _mainLayoutAnimeIndexRoute,
  _mainLayoutMovieIndexRoute: _mainLayoutMovieIndexRoute,
  _mainLayoutProfileIndexRoute: _mainLayoutProfileIndexRoute,
  _mainLayoutSeriesIndexRoute: _mainLayoutSeriesIndexRoute,
}

const _mainLayoutRouteWithChildren = _mainLayoutRoute._addFileChildren(
  _mainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authLayoutRoute: _authLayoutRouteWithChildren,
  _mainLayoutRoute: _mainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
