/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _mainLayoutRouteImport } from './routes/__mainLayout'
import { Route as _mainLayoutIndexRouteImport } from './routes/__mainLayout/index'
import { Route as _mainLayoutSeriesRouteImport } from './routes/__mainLayout/series'
import { Route as _mainLayoutMovieRouteImport } from './routes/__mainLayout/movie'
import { Route as _mainLayoutHomeRouteImport } from './routes/__mainLayout/home'
import { Route as _mainLayoutAnimeRouteImport } from './routes/__mainLayout/anime'

const _mainLayoutRoute = _mainLayoutRouteImport.update({
  id: '/__mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const _mainLayoutIndexRoute = _mainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutSeriesRoute = _mainLayoutSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutMovieRoute = _mainLayoutMovieRouteImport.update({
  id: '/movie',
  path: '/movie',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutHomeRoute = _mainLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutAnimeRoute = _mainLayoutAnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => _mainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _mainLayoutIndexRoute
  '/anime': typeof _mainLayoutAnimeRoute
  '/home': typeof _mainLayoutHomeRoute
  '/movie': typeof _mainLayoutMovieRoute
  '/series': typeof _mainLayoutSeriesRoute
}
export interface FileRoutesByTo {
  '/anime': typeof _mainLayoutAnimeRoute
  '/home': typeof _mainLayoutHomeRoute
  '/movie': typeof _mainLayoutMovieRoute
  '/series': typeof _mainLayoutSeriesRoute
  '/': typeof _mainLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__mainLayout': typeof _mainLayoutRouteWithChildren
  '/__mainLayout/anime': typeof _mainLayoutAnimeRoute
  '/__mainLayout/home': typeof _mainLayoutHomeRoute
  '/__mainLayout/movie': typeof _mainLayoutMovieRoute
  '/__mainLayout/series': typeof _mainLayoutSeriesRoute
  '/__mainLayout/': typeof _mainLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anime' | '/home' | '/movie' | '/series'
  fileRoutesByTo: FileRoutesByTo
  to: '/anime' | '/home' | '/movie' | '/series' | '/'
  id:
    | '__root__'
    | '/__mainLayout'
    | '/__mainLayout/anime'
    | '/__mainLayout/home'
    | '/__mainLayout/movie'
    | '/__mainLayout/series'
    | '/__mainLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _mainLayoutRoute: typeof _mainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__mainLayout': {
      id: '/__mainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _mainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__mainLayout/': {
      id: '/__mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _mainLayoutIndexRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/series': {
      id: '/__mainLayout/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof _mainLayoutSeriesRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/movie': {
      id: '/__mainLayout/movie'
      path: '/movie'
      fullPath: '/movie'
      preLoaderRoute: typeof _mainLayoutMovieRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/home': {
      id: '/__mainLayout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof _mainLayoutHomeRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/anime': {
      id: '/__mainLayout/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof _mainLayoutAnimeRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
  }
}

interface _mainLayoutRouteChildren {
  _mainLayoutAnimeRoute: typeof _mainLayoutAnimeRoute
  _mainLayoutHomeRoute: typeof _mainLayoutHomeRoute
  _mainLayoutMovieRoute: typeof _mainLayoutMovieRoute
  _mainLayoutSeriesRoute: typeof _mainLayoutSeriesRoute
  _mainLayoutIndexRoute: typeof _mainLayoutIndexRoute
}

const _mainLayoutRouteChildren: _mainLayoutRouteChildren = {
  _mainLayoutAnimeRoute: _mainLayoutAnimeRoute,
  _mainLayoutHomeRoute: _mainLayoutHomeRoute,
  _mainLayoutMovieRoute: _mainLayoutMovieRoute,
  _mainLayoutSeriesRoute: _mainLayoutSeriesRoute,
  _mainLayoutIndexRoute: _mainLayoutIndexRoute,
}

const _mainLayoutRouteWithChildren = _mainLayoutRoute._addFileChildren(
  _mainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _mainLayoutRoute: _mainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
